# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:


    encoders:
        FOS\RentBundle\ClientInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN:      ROLE_USER
        ROLE_SUPER_USER: ROLE_ADMIN

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        fos_clientbundle:
            id: fos_client.client_provider.username

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        main:
            dev:
                pattern: ^/(_(profiler|wdt)|css|images|js)/
                security: false
            pattern: ^/
            form_login:
                provider: fos_clientbundle
                csrf_token_generator: security.csrf_token_manager
            logout:       true
            anonymous:    true

    access_control:
        - {path: ^/logins$, role: IS_AUTHENTICATED_ANONYMOUSLY}
        - {path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY}
        - {path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY}
        - {path: ^/admin/, role: ROLE_ADMIN}
#        main:
#            anonymous: ~
            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
